version: '3.7'

x-fediverser-service: &fediverser-service
  image: "fediverser/app:${TAG:-latest}"
  command: poetry run uvicorn fediverser.services.base.asgi:application --port 80 --host 0.0.0.0

  environment: &fediverser-service-environment
    DJANGO_SETTINGS_MODULE: fediverser.services.base.settings

services:
  admin:
    <<: *fediverser-service
    environment:
      <<: *fediverser-service-environment
      FEDIVERSER_ROOT_URLCONF: fediverser.services.admin.urls

  portal:
    <<: *fediverser-service
    environment:
      <<: *fediverser-service-environment
      FEDIVERSER_ROOT_URLCONF: fediverser.services.portal.urls

  celery:
    <<: *fediverser-service
    command: poetry run celery -A fediverser.services.base worker -l INFO -E

  celerybeat:
    <<: *fediverser-service
    command: poetry run celery -A fediverser.services.base beat -l INFO -S django

  init_migrate_db:
    <<: *fediverser-service
    command: poetry run django-admin migrate

  init_collect_static:
    <<: *fediverser-service
    command: poetry run django-admin collectstatic --no-input
