[tool.black]
line-length = 99
target-version = ['py310', 'py311']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | build
  | dist
)/
'''

[tool.isort]
py_version = 311
line_length = 99
default_section = "THIRDPARTY"
combine_as_imports = true
order_by_type = true
profile = "black"
known_first_party = "fediverser"

[tool.poetry]
name = "fediverser"
version = "0.2.0"
description = "Tools to help bring content from legacy networks to the Fediverse"
authors = ["Raphael Lullis <raphael@mushroomlabs.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
praw = "^7.7"
pythorhead = "^0.15.6"
requests = "^2"
langdetect = "^1.0"
django = "^4.2"
django-environ = "^0.10"
django-allauth = "^0.57"
celery = "^5"
uvicorn = {extras = ["standard"], version = "^0.23"}
django-celery-beat = "^2.5"
psycopg2-binary = "^2.9"
redis = "^5"
requests-cache = "^1.1"
factory-boy = "^3.3"
django-redis = "^5.3"
django-extensions = "^3.2"
django-model-utils = "^4.3"
django-celery-results = "^2.5"
bcrypt = "^4.0"
pycryptodome = "^3"
pytest = "^7.4"
pytest-env = "^1.0"
pytest-django = "^4.5"
django-compressor = "^4.4"
pysass = "^0.1.0"

[tool.poetry.group.dev.dependencies]
ipython = "^8.14.0"
black = "^23.7.0"
isort = "^5.12.0"
flake8 = "^6.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
